// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhuZhuBot;

#nullable disable

namespace ZhuZhuBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ZhuZhuBot.DbModels.CpdailyLoginResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolAppCookie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SchoolAppCookieUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tgc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CpdailyLoginResult");
                });

            modelBuilder.Entity("ZhuZhuBot.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpdailyLoginResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchooldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CpdailyLoginResultId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZhuZhuBot.DbModels.User", b =>
                {
                    b.HasOne("ZhuZhuBot.DbModels.CpdailyLoginResult", "CpdailyLoginResult")
                        .WithMany()
                        .HasForeignKey("CpdailyLoginResultId");

                    b.Navigation("CpdailyLoginResult");
                });
#pragma warning restore 612, 618
        }
    }
}
